ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += sx1262
  # DIO3 is used as TXCO, so this module required
  USEMODULE += sx126x_dio3
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

include $(RIOTBOARD)/common/esp32s3/Makefile.dep
