CPU_MODEL = esp32s3

# common board and CPU features
include $(RIOTBOARD)/common/esp32s3/Makefile.features

# additional features provided by the board
FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_spi
